.catalog:
    name: "Graylog"
    version: "v2.1.0-1"
    description: "Open source log management that actually works. Pour le port 9000, veuillez passer par un nouveau LoadBalancer si vous voulez le rendre public"
    questions:
        - variable: graylog_password
          description: "Password in sha2"
          label: "SHA2 Password"
          type: "string"
          required: true
        - variable: graylog_secret
          description: "Password secret"
          label: "Password secret"
          type: "string"
          required: true
        - variable: graylog_fqdn
          description: "IP ou Nom de domaine du serveur"
          label: "FQDN"
          type: "string"
          required: true
        - variable: graylog_mail_enable
          description: "Activate emails"
          label: "Mails:"
          type: "string"
          required: true
          default: true
        - variable: graylog_mail_hostname
          description: "Hostname adresse of smtp server"
          label: "Smtp hostname:"
          type: "string"
          required: true
        - variable: graylog_mail_port
          description: "Smtp port to connect"
          label: "Smtp port:"
          type: "string"
          required: true
          default: 25
        - variable: graylog_mail_use_ssl_auth
          description: "Use ssl authentification"
          label: "SSL Auth:"
          type: "string"
          required: true
          default: false
        - variable: graylog_mail_use_ssl
          description: "Use ssl connection"
          label: "SSL:"
          type: "string"
          required: true
          default: false
        - variable: graylog_mail_use_tls
          description: "Use tls connection"
          label: "TLS:"
          type: "string"
          required: true
          default: false
        - variable: es_service
          description: "Service ElasticSearch"
          label: "Service ElasticSearch"
          type: "service"
          required: true