version: '2'
services:

  wordpress:
    image: wordpress:php5.6-fpm-alpine
    environment:
      WORDPRESS_DB_PASSWORD: ${sql_wordpress_password}
      WORDPRESS_DB_USER: ${sql_wordpress_name}
      WORDPRESS_DB_NAME: ${sql_wordpress_name}
    links:
      - db:mysql
    labels:
      traefik.enable: ${lb_enable}
      traefik.domain: ${lb_domain}
      traefik.protocol: ${lb_proto}
      traefik.alias.fqdn: ${domain}
      traefik.port: ${port}
      traefik.acme: ${letsencrypt}
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${sql_root_password}
      MYSQL_DATABASE: ${sql_wordpress_name}
      MYSQL_USER: ${sql_wordpress_name}
      MYSQL_PASSWORD: ${sql_wordpress_password}


volumes:
  lets-encrypt:
    driver: ${STORAGE_DRIVER}
