version: '2'
services:

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_PASSWORD: ${sql_wordpress_password}
      WORDPRESS_DB_USER: ${sql_wordpress_name}
      WORDPRESS_DB_NAME: ${sql_wordpress_name}
    links:
      - db:mysql
    labels:
      io.rancher.sidekicks: wordpress-data
      traefik.enable: ${lb_enable}
      traefik.domain: ${lb_domain}
      traefik.protocol: ${lb_proto}
      traefik.alias.fqdn: ${domain}
      traefik.port: ${port}
      traefik.acme: ${letsencrypt}
      traefik.frontend.passHostHeader: 'true'
      io.rancher.container.hostname_override: container_name
    volumes_from:
      - wordpress-data

  db:
    image: mariadb
    labels:
      io.rancher.sidekicks: wordpress-data
    environment:
      MYSQL_ROOT_PASSWORD: ${sql_root_password}
      MYSQL_DATABASE: ${sql_wordpress_name}
      MYSQL_USER: ${sql_wordpress_name}
      MYSQL_PASSWORD: ${sql_wordpress_password}
    volumes_from:
      - wordpress-data

  wordpress-data:
    image: wordpress:latest
    entrypoint:
      - /bin/true
    volumes:
      - /var/www/html/
      - /var/lib/mysql

