version: '2'
services:

  wordpress:
    image: wordpress:latest
    ports:
      - "80"
    environment:
      WORDPRESS_DB_PASSWORD: ${sql_wordpress_password}
      WORDPRESS_DB_USER: ${sql_wordpress_name}
      WORDPRESS_DB_NAME: ${sql_wordpress_name}
    links:
      - db:mysql
    labels:
      traefik.enable: ${lb_enable}
      traefik.domain: ${lb_domain}
      traefik.protocol: ${lb_proto}
      traefik.alias.fqdn: ${domain}
      traefik.port: ${port}
      traefik.acme: ${letsencrypt}
      traefik.frontend.passHostHeader: 'true'
      io.rancher.container.hostname_override: container_name
    volumes_from:
      - data
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${sql_root_password}
      MYSQL_DATABASE: ${sql_wordpress_name}
      MYSQL_USER: ${sql_wordpress_name}
      MYSQL_PASSWORD: ${sql_wordpress_password}
    volumes_from:
      - data

  data:
    tty: true
    image: busybox:latest
    labels:
      io.rancher.sidekicks: db, wordpress
      io.rancher.container.start_once: 'true'
    volumes:
      - /var/www/html/
      - /var/lib/mysql


