version: '2'
services:

  wordpress:
    image: wordpress
    links:
      - db:mysql

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${sql_root_password}

  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.4.0
    environment:
      EULA: ${EULA}
      API_VERSION: ${API_VERSION}
      CERT_NAME: ${CERT_NAME}
      EMAIL: ${EMAIL}
      DOMAINS: ${DOMAINS}
      PUBLIC_KEY_TYPE: ${PUBLIC_KEY_TYPE}
      RENEWAL_TIME: ${RENEWAL_TIME}
      PROVIDER: ${PROVIDER}
    volumes:
      - lets-encrypt:/etc/letsencrypt
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'

volumes:
  lets-encrypt:
    driver: ${STORAGE_DRIVER}
