.catalog:
  name: "Wordpress boTux"
  version: "v0.2.3-botux-ssl"
  description: "Blog tool, publishing platform and CMS"
  uuid: Wordpress-1
  minimum_rancher_version: v0.51.0
  questions:    
    - variable: lb_domain
      description: "domain traefik"
      label: "LB domain"
      required: true
      default: "BIG_STRONG_PASSWORD"
      type: "string"
    - variable: sql_root_password
      description: "SQL root password"
      label: "SQL password"
      required: true
      default: "BIG_STRONG_PASSWORD"
      type: "string"
    - variable: sql_wordpress_password
      description: "SQL wordpress password"
      label: "SQL password"
      required: true
      default: "BIG_STRONG_PASSWORD"
      type: "string"
    - variable: sql_wordpress_name
      description: "SQL wordpress name"
      label: "SQL DB Name"
      required: true
      default: "wordpress"
      type: "string"
    - variable: lb_enable
      description: "Acticate traefik"
      label: "LoadBalancer"
      required: true
      default: "true"
      type: "string"
    - variable: lb_proto
      description: "http or https"
      label: "Protocol"
      required: true
      default: "https"
      type: "string"
    - variable: domain
      description: "url of the site"
      label: "Domain"
      required: false
      default: "wordpress.site.xyz"
      type: "string"
    - variable: port
      description: "port to link"
      label: "Port"
      required: true
      default: "80"
      type: "string"
    - variable: letsencrypt
      description: "Cert ssl letsencrypt"
      label: "SSL"
      required: true
      default: "true"
      type: "string"
wordpress:
  health_check:
    port: 80
    interval: 5000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 5000
data:
  scale: 1
  retain_ip: true
