db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: ${sql_root_password}
    MYSQL_DATABASE: ${sql_joomla_name}
    MYSQL_USER: ${sql_joomla_name}
    MYSQL_PASSWORD: ${sql_joomla_password}
  volumes:
    - ${projet_name}-sql:/var/lib/mysql

joomla:
  restart: always
  image: registry.enigm.com/sysadmin/docker/webapps/joomla:latest
  environment:
    JOOMLA_DB_PASSWORD: ${sql_joomla_password}
    JOOMLA_DB_USER: ${sql_joomla_name}
    JOOMLA_DB_NAME: ${sql_joomla_name}
  volumes:
    - ${projet_name}-joomla:/usr/src/joomla
    - ${projet_name}-www:/var/www/html
  links:
    - db:mysql
  labels:
    io.rancher.container.hostname_override: container_name
    traefik.enable: ${lb_enable}
    traefik.domain: ${lb_domain}
    traefik.protocol: ${lb_proto}
    traefik.alias.fqdn: ${domain}
    traefik.port: ${port}
    traefik.acme: ${letsencrypt}
    traefik.frontend.passHostHeader: 'true'

mail:
  image: tozd/postfix
  environment:
    MY_NETWORKS: ${postfix_network}
    ROOT_ALIAS: ${postfix_root_alias}
    MAILNAME: ${postfix_mailname}
  stdin_open: true
  volumes:
    - ${projet_name}-postfix-log:/var/log/postfix
    - ${projet_name}-postfix-spool:/var/spool/postfix
  tty: true

pma:
  image: phpmyadmin/phpmyadmin
  stdin_open: true
  tty: true
  links:
    - db:db
  labels:
    traefik.enable: ${lb_enable}
    traefik.domain: ${lb_domain}
    traefik.protocol: http
    traefik.alias.fqdn: ${domain}
    traefik.port: 80
    traefik.acme: ${letsencrypt}
    traefik.frontend.passHostHeader: 'true'

sftp:
  image: atmoz/sftp
  stdin_open: true
  volumes:
    - ${projet_name}-www:/home/${sftp_user}/${projet_name}/www
  tty: true
  ports:
    - ${sftp_port}:22/tcp
  command:
    - ${sftp_user}:${sftp_pass}:${sftp_group}
